/**
 * T021, T027, T028, T041 — case documents: upload (reserve-then-commit), list,
 * find-in-case, withdraw, restore. Metadata rows only — no bytes ever pass through
 * here (research.md D6).
 */
import { Injectable } from '@nestjs/common';
import { sql } from 'drizzle-orm';
import { currentTx } from '../../common/tenant/middleware';
import { toPage, type Cursor, type Page } from '../../common/http/pagination';
import { LIKE_ESCAPE_CHAR, escapeLike } from './like-escape';

export interface DocumentRow {
  readonly id: string;
  readonly tenantId: string;
  readonly caseId: string;
  readonly uploadedByMembershipId: string;
  readonly categoryId: string;
  readonly categoryName: string;
  readonly categoryStatus: 'active' | 'retired';
  readonly storageKey: string;
  readonly originalFilename: string;
  readonly mimeType: string;
  readonly sizeBytes: number;
  readonly status: 'active' | 'withdrawn';
  readonly uploadedAt: string;
  readonly withdrawnAt: string | null;
}

interface RawDocumentRow {
  id: string;
  tenant_id: string;
  case_id: string;
  uploaded_by_membership_id: string;
  category_id: string;
  category_name: string;
  category_status: 'active' | 'retired';
  storage_key: string;
  original_filename: string;
  mime_type: string;
  size_bytes: string;
  status: 'active' | 'withdrawn';
  uploaded_at: string;
  withdrawn_at: string | null;
  [key: string]: unknown;
}

/**
 * 023 — a firm-wide list item. `DocumentRow` plus the matter's file number, which is what a
 * card outside a case needs in order to say which matter it belongs to.
 *
 * `storageKey` is deliberately ABSENT: it is an internal pointer, the per-case presenter does
 * not expose it either, and a firm-wide list is the last place to start.
 */
export interface FirmDocumentRow {
  readonly id: string;
  readonly caseId: string;
  readonly caseFileNumber: string;
  readonly uploadedByMembershipId: string;
  readonly categoryId: string;
  readonly categoryName: string;
  readonly categoryStatus: 'active' | 'retired';
  readonly originalFilename: string;
  readonly mimeType: string;
  readonly sizeBytes: number;
  readonly status: 'active' | 'withdrawn';
  readonly uploadedAt: string;
  readonly withdrawnAt: string | null;
}

interface RawFirmDocumentRow {
  id: string;
  tenant_id: string;
  case_id: string;
  case_file_number: string;
  uploaded_by_membership_id: string;
  category_id: string;
  category_name: string;
  category_status: 'active' | 'retired';
  original_filename: string;
  mime_type: string;
  size_bytes: string;
  status: 'active' | 'withdrawn';
  uploaded_at: string;
  withdrawn_at: string | null;
  [key: string]: unknown;
}

const presentFirm = (row: RawFirmDocumentRow): FirmDocumentRow => ({
  id: row.id,
  caseId: row.case_id,
  caseFileNumber: row.case_file_number,
  uploadedByMembershipId: row.uploaded_by_membership_id,
  categoryId: row.category_id,
  categoryName: row.category_name,
  categoryStatus: row.category_status,
  originalFilename: row.original_filename,
  mimeType: row.mime_type,
  sizeBytes: Number(row.size_bytes),
  status: row.status,
  uploadedAt: row.uploaded_at,
  withdrawnAt: row.withdrawn_at,
});

export interface ListFirmDocumentsInput {
  readonly limit: number;
  readonly cursor?: Cursor;
  /** True for MP and SA — the archetypes the `assigned` resolver satisfies unconditionally. */
  readonly unrestricted: boolean;
  readonly membershipId: string;
  readonly q?: string;
  readonly categoryId?: string;
  readonly caseId?: string;
}

/** The envelope, extended with `total` — 023 Decision 3. */
export interface FirmDocumentsPage extends Page<FirmDocumentRow> {
  readonly total: number;
}

const SELECT_WITH_CATEGORY = sql`
  SELECT d.id, d.tenant_id, d.case_id, d.uploaded_by_membership_id, d.category_id,
         c.name AS category_name, c.status AS category_status,
         d.storage_key, d.original_filename, d.mime_type, d.size_bytes,
         d.status, d.uploaded_at, d.withdrawn_at
    FROM document d
    JOIN document_category c ON c.id = d.category_id
`;

const present = (row: RawDocumentRow): DocumentRow => ({
  id: row.id,
  tenantId: row.tenant_id,
  caseId: row.case_id,
  uploadedByMembershipId: row.uploaded_by_membership_id,
  categoryId: row.category_id,
  categoryName: row.category_name,
  categoryStatus: row.category_status,
  storageKey: row.storage_key,
  originalFilename: row.original_filename,
  mimeType: row.mime_type,
  sizeBytes: Number(row.size_bytes),
  status: row.status,
  uploadedAt: row.uploaded_at,
  withdrawnAt: row.withdrawn_at,
});

export interface NewDocument {
  /** Generated by the service BEFORE insert, so the S3 key (research.md D6) can be
   * built deterministically from it ahead of the write. */
  readonly id: string;
  readonly caseId: string;
  readonly tenantId: string;
  readonly uploadedByMembershipId: string;
  readonly categoryId: string;
  readonly storageKey: string;
  readonly originalFilename: string;
  readonly mimeType: string;
  readonly sizeBytes: number;
}

@Injectable()
export class DocumentsRepository {
  /**
   * RLS-scoped. A foreign or absent case resolves to `null` — needed because
   * `006`'s `AssignedScopeResolver` grants `MP`/`SA` unconditionally BEFORE checking
   * whether the named case exists at all (Decision 2's own short-circuit); without
   * this check here, uploading against a nonexistent case as `MP`/`SA` would surface
   * as a raw foreign-key violation (500) rather than the generic `404` every other
   * "no such case" reach in this system produces.
   */
  async findCase(caseId: string): Promise<{ id: string; tenantId: string } | null> {
    const { rows } = await currentTx().execute<{ id: string; tenant_id: string }>(sql`
      SELECT id, tenant_id FROM case_file WHERE id = ${caseId}::uuid
    `);
    const row = rows[0];
    return row ? { id: row.id, tenantId: row.tenant_id } : null;
  }

  /** RLS-scoped. A retired or foreign category resolves to `null`. */
  async findCategory(categoryId: string): Promise<{ id: string; name: string; status: string } | null> {
    const { rows } = await currentTx().execute<{ id: string; name: string; status: string }>(sql`
      SELECT id, name, status FROM document_category WHERE id = ${categoryId}::uuid
    `);
    return rows[0] ?? null;
  }

  /** FR-010's default — resolved by name, per tenant, under RLS. Always `active`
   * by construction (the query filters on it), included for type parity with
   * `findCategory`'s return shape. */
  /**
   * 007/FR-010's default. 021 Decision 5 renamed it "Sin clasificar" (migration 0045); the English
   * name is still accepted for a firm that had created its own "Sin clasificar" and so kept both,
   * and the Spanish one wins when both exist.
   */
  async findDefaultCategory(): Promise<{ id: string; name: string; status: string } | null> {
    const { rows } = await currentTx().execute<{ id: string; name: string; status: string }>(sql`
      SELECT id, name, status FROM document_category
       WHERE lower(trim(name)) IN ('sin clasificar', 'unclassified') AND status = 'active'
       ORDER BY (lower(trim(name)) = 'sin clasificar') DESC
       LIMIT 1
    `);
    return rows[0] ?? null;
  }

  /** research.md D3 — read live, never cached (FR-014). */
  /**
   * research.md D4 — the check and the increment are ONE atomic statement, not a
   * `SELECT` followed by an `UPDATE`. Two concurrent transactions each reading the
   * pre-update total and then both committing an increment is exactly the race
   * `spec.md`'s Edge Cases named — a plain `SELECT` cannot see an increment a
   * concurrent, not-yet-committed transaction is mid-way through, but Postgres's
   * own row lock on `UPDATE` DOES serialize two writers, so folding the limit
   * check into the `WHERE` clause of the increment itself is what makes the second
   * writer's check run against the FIRST writer's already-applied total rather than
   * a stale value read before either committed.
   *
   * Returns `false` (nothing reserved) when reserving would exceed `limitBytes`.
   * `limitBytes: null` means the tenant's plan carries no configured ceiling — the
   * increment always succeeds, matching every other quantitative check in this
   * product treating "no limit key" as "no restriction" (004/`capabilityDef`'s own
   * fallback).
   */
  async reserveStorage(tenantId: string, sizeBytes: number, limitBytes: number | null): Promise<boolean> {
    const { rows } = await currentTx().execute<{ id: string }>(sql`
      UPDATE tenant
         SET storage_bytes_used = storage_bytes_used + ${sizeBytes}
       WHERE id = ${tenantId}::uuid
         ${limitBytes === null ? sql`` : sql`AND storage_bytes_used + ${sizeBytes} <= ${limitBytes}`}
       RETURNING id
    `);
    return rows.length > 0;
  }

  /** research.md D3 — read live, never cached (FR-014). Diagnostic/display use only —
   * `reserveStorage` above is what actually enforces the limit atomically. */
  async currentStorageUsage(tenantId: string): Promise<number> {
    const { rows } = await currentTx().execute<{ storage_bytes_used: string }>(sql`
      SELECT storage_bytes_used FROM tenant WHERE id = ${tenantId}::uuid
    `);
    return Number(rows[0]?.storage_bytes_used ?? 0);
  }

  /**
   * The metadata row only — `reserveStorage` above already reserved the headroom
   * in its own statement before this is called.
   */
  async insertDocument(input: NewDocument): Promise<DocumentRow> {
    const { rows } = await currentTx().execute<RawDocumentRow>(sql`
      WITH inserted AS (
        INSERT INTO document (id, case_id, tenant_id, uploaded_by_membership_id, category_id, storage_key, original_filename, mime_type, size_bytes)
        VALUES (${input.id}::uuid, ${input.caseId}::uuid, ${input.tenantId}::uuid, ${input.uploadedByMembershipId}::uuid, ${input.categoryId}::uuid, ${input.storageKey}, ${input.originalFilename}, ${input.mimeType}, ${input.sizeBytes})
        RETURNING *
      )
      SELECT inserted.id, inserted.tenant_id, inserted.case_id, inserted.uploaded_by_membership_id,
             inserted.category_id, c.name AS category_name, c.status AS category_status,
             inserted.storage_key, inserted.original_filename, inserted.mime_type, inserted.size_bytes,
             inserted.status, inserted.uploaded_at, inserted.withdrawn_at
        FROM inserted
        JOIN document_category c ON c.id = inserted.category_id
    `);
    const row = rows[0];
    if (!row) throw new Error('document insert returned no row');
    return present(row);
  }

  /**
   * research.md D4 — the compensating rollback for a failed S3 write. Reverses
   * exactly the reservation `insertReservingStorage` made, in its own transaction
   * (the original one has already committed by the time an S3 failure is known).
   */
  async rollbackReservation(documentId: string, tenantId: string, sizeBytes: number): Promise<void> {
    await currentTx().execute(sql`
      UPDATE tenant SET storage_bytes_used = storage_bytes_used - ${sizeBytes} WHERE id = ${tenantId}::uuid
    `);
    await currentTx().execute(sql`DELETE FROM document WHERE id = ${documentId}::uuid`);
  }

  /** T027 — a document that exists but belongs to a different case resolves to `null`,
   * the same generic not-found an absent document produces (FR-007's opacity). */
  async findInCase(id: string, caseId: string): Promise<DocumentRow | null> {
    const { rows } = await currentTx().execute<RawDocumentRow>(sql`
      ${SELECT_WITH_CATEGORY}
      WHERE d.id = ${id}::uuid AND d.case_id = ${caseId}::uuid
    `);
    const row = rows[0];
    return row ? present(row) : null;
  }

  /** T028 — every active document referencing this case (contracts/document-api.md §2). */
  async listByCase(caseId: string): Promise<readonly DocumentRow[]> {
    const { rows } = await currentTx().execute<RawDocumentRow>(sql`
      ${SELECT_WITH_CATEGORY}
      WHERE d.case_id = ${caseId}::uuid AND d.status = 'active'
      ORDER BY d.uploaded_at DESC
    `);
    return rows.map(present);
  }

  /**
   * 023 — the firm's documents, across every case the caller can reach. FR-001 … FR-008.
   *
   * WHY THE PREDICATES ARE BUILT ONCE AND USED TWICE, which is the whole design of this
   * method: the page and the `total` MUST describe the same set. A count computed under a
   * different `WHERE` would tell an `AA` how many documents exist on matters they cannot
   * reach — a quantitative leak under Principle II, and the single most likely way this
   * endpoint could ship broken, because two queries in two places drift. There is one
   * `conditions` array; both queries consume it.
   *
   * WHY THE ASSIGNMENT PREDICATE IS HERE rather than in the interceptor: a scope resolver
   * returns a boolean, so an `assigned`-scoped capability could only REFUSE a member with no
   * assignments, where the spec requires an empty list. `case.read_list` reached the same
   * conclusion and `tests/contract/case-list-scoping.test.ts` exists to stop it being
   * "tidied" back. The predicate below is `case.repository.ts:156-162`'s, moved one join over.
   *
   * No `tenant_id` predicate: RLS does that, as everywhere else in this file.
   */
  async listForTenant(input: ListFirmDocumentsInput): Promise<FirmDocumentsPage> {
    const conditions = [sql`d.status = 'active'`];

    if (!input.unrestricted) {
      conditions.push(sql`EXISTS (
        SELECT 1 FROM case_assignment a
         WHERE a.case_id = d.case_id
           AND a.membership_id = ${input.membershipId}::uuid
           AND a.unassigned_at IS NULL
      )`);
    }

    if (input.q !== undefined) {
      // One parenthesised group, so a later condition ANDed on cannot be swallowed by the OR
      // — the same reason `case.repository.ts:140-152` spells it out. The term is escaped
      // (FR-008) and the escape character is named rather than assumed.
      const term = `%${escapeLike(input.q)}%`;
      conditions.push(sql`(
        d.original_filename ILIKE ${term} ESCAPE ${LIKE_ESCAPE_CHAR}
        OR cf.file_number ILIKE ${term} ESCAPE ${LIKE_ESCAPE_CHAR}
      )`);
    }

    if (input.categoryId !== undefined) {
      conditions.push(sql`d.category_id = ${input.categoryId}::uuid`);
    }
    if (input.caseId !== undefined) {
      conditions.push(sql`d.case_id = ${input.caseId}::uuid`);
    }

    const where = sql.join(conditions, sql` AND `);

    // The count runs BEFORE the cursor is applied, deliberately: `total` describes the whole
    // filtered set, which is what "128 documentos" means on screen, not the current page.
    const counted = await currentTx().execute<{ total: string }>(sql`
      SELECT count(*)::text AS total
        FROM document d
        JOIN case_file cf ON cf.id = d.case_id
       WHERE ${where}
    `);

    const paged = [...conditions];
    if (input.cursor) {
      paged.push(
        sql`(d.uploaded_at, d.id) < (${input.cursor.occurredAt}::timestamptz, ${input.cursor.id}::uuid)`,
      );
    }

    const { rows } = await currentTx().execute<RawFirmDocumentRow>(sql`
      SELECT d.id, d.tenant_id, d.case_id, d.uploaded_by_membership_id, d.category_id,
             c.name AS category_name, c.status AS category_status,
             d.original_filename, d.mime_type, d.size_bytes,
             d.status, d.uploaded_at, d.withdrawn_at,
             cf.file_number AS case_file_number
        FROM document d
        JOIN document_category c ON c.id = d.category_id
        JOIN case_file cf ON cf.id = d.case_id
       WHERE ${sql.join(paged, sql` AND `)}
       ORDER BY d.uploaded_at DESC, d.id DESC
       LIMIT ${input.limit + 1}
    `);

    const page = toPage(rows.map(presentFirm), input.limit, (row) => ({
      occurredAt: row.uploadedAt,
      id: row.id,
    }));

    return { ...page, total: Number(counted.rows[0]?.total ?? '0') };
  }

  /**
   * 021 Decision 2 — the case's withdrawn documents, most recently withdrawn first. The only
   * read that can find one again, so the only way `restore` is reachable from a screen.
   */
  async listWithdrawnByCase(caseId: string): Promise<readonly DocumentRow[]> {
    const { rows } = await currentTx().execute<RawDocumentRow>(sql`
      ${SELECT_WITH_CATEGORY}
      WHERE d.case_id = ${caseId}::uuid AND d.status = 'withdrawn'
      ORDER BY d.withdrawn_at DESC
    `);
    return rows.map(present);
  }

  async updateCategory(id: string, categoryId: string): Promise<DocumentRow> {
    await currentTx().execute(sql`
      UPDATE document SET category_id = ${categoryId}::uuid WHERE id = ${id}::uuid
    `);
    const row = await this.findByIdOnly(id);
    if (!row) throw new Error('document not found after category update');
    return row;
  }

  /** T041 — status + timestamp only; never touches storage_bytes_used (research.md D3). */
  async withdraw(id: string): Promise<DocumentRow> {
    await currentTx().execute(sql`
      UPDATE document SET status = 'withdrawn', withdrawn_at = now() WHERE id = ${id}::uuid
    `);
    const row = await this.findByIdOnly(id);
    if (!row) throw new Error('document not found after withdraw');
    return row;
  }

  async restore(id: string): Promise<DocumentRow> {
    await currentTx().execute(sql`
      UPDATE document SET status = 'active', withdrawn_at = NULL WHERE id = ${id}::uuid
    `);
    const row = await this.findByIdOnly(id);
    if (!row) throw new Error('document not found after restore');
    return row;
  }

  private async findByIdOnly(id: string): Promise<DocumentRow | null> {
    const { rows } = await currentTx().execute<RawDocumentRow>(sql`
      ${SELECT_WITH_CATEGORY}
      WHERE d.id = ${id}::uuid
    `);
    const row = rows[0];
    return row ? present(row) : null;
  }
}
