/**
 * T048 — the header stand-ins are gone. FR-041, SC-030, research.md D10.
 *
 * 002 shipped `x-identity-id`, `x-subject` and `x-email` as deliberate
 * stand-ins, on a condition it wrote down: "real verification does not exist
 * until slice 003". That condition is now met, and the debt falls due — these
 * headers must be accepted on ZERO network-reachable surfaces.
 *
 * `x-tenant-id` STAYS, and the distinction is the point of this file. It was
 * never an identity claim: it names WHICH of the caller's memberships to
 * activate, chosen by a person who may hold several (001/FR-021), and
 * `membership` under RLS is what decides whether they may. Removing it would
 * break 002/FR-013 for no security gain — it asserts nothing, it selects.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import request from 'supertest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import type { INestApplication } from '@nestjs/common';
import type { Client } from 'pg';
import { createUnauthenticatedApp } from '../helpers/real-app';
import { connectAs } from '../helpers/db';
import { seededTenantIds, type SeededTenants } from '../helpers/tenants';
import { seedAuthIdentity, TEST_CREDENTIAL } from '../helpers/auth-seed';
import { generateAt } from '../../src/common/auth/totp';
import { signInOriginThrottle } from '../../src/common/auth/origin-throttle';

const REMOVED = ['x-identity-id', 'x-subject', 'x-email'] as const;

function sourceFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) sourceFiles(full, out);
    else if (full.endsWith('.ts')) out.push(full);
  }
  return out;
}

describe('the header stand-ins are gone (FR-041, SC-030, D10)', () => {
  let app: INestApplication;
  let migration: Client;
  let tenants: SeededTenants;

  beforeAll(async () => {
    // The UNAUTHENTICATED app: the stand-in lives only in the test helper, and
    // this suite must not be holding the very thing it claims is gone.
    app = await createUnauthenticatedApp();
    migration = await connectAs('migration');
    tenants = await seededTenantIds();
  });

  afterAll(async () => {
    await app.close();
    await migration.end();
  });

  it('0 src/** files read any of the three headers', async () => {
    // The strongest form of the claim. A route that never reads the header
    // cannot be fooled by one, whatever the middleware does.
    // Comments are stripped first. Several files MENTION these headers to
    // explain that they are gone and why, and treating an explanation as a
    // violation would push the next person to delete the explanation rather
    // than keep the property.
    const stripComments = (text: string): string =>
      text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');

    const offenders: string[] = [];
    for (const file of sourceFiles(join(__dirname, '..', '..', 'src'))) {
      const code = stripComments(readFileSync(file, 'utf8'));
      for (const header of REMOVED) {
        if (code.includes(header)) offenders.push(`${file} reads ${header}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('presenting them buys nothing on a tenant-scoped route', async () => {
    const identity = await seedAuthIdentity(migration, 'standins-tenant');
    await migration.query(
      `INSERT INTO membership (identity_id, tenant_id, archetype) VALUES ($1, $2, 'SA')`,
      [identity.identityId, tenants.a],
    );

    const response = await request(app.getHttpServer())
      .get('/tenant/invitations')
      .set('x-identity-id', identity.identityId)
      .set('x-tenant-id', tenants.a);

    // A real membership, a real tenant, and the header that used to be enough.
    // 401, because none of it is proof.
    expect(response.status).toBe(401);
  });

  it('presenting them buys nothing on the identity-only route either', async () => {
    const identity = await seedAuthIdentity(migration, 'standins-identity');
    const response = await request(app.getHttpServer())
      .get('/identity/memberships')
      .set('x-identity-id', identity.identityId);
    expect(response.status).toBe(401);
  });

  it('x-subject and x-email buy nothing at acceptance', async () => {
    // These two named WHO was accepting. The subject is now generated by the
    // product, and the email arrives in the body — a header cannot substitute
    // for either.
    const response = await request(app.getHttpServer())
      .post('/identity/invitations/some-reference/accept')
      .set('x-subject', 'idp|somebody-else')
      .set('x-email', 'somebody@example.com')
      .send({});
    expect(response.status).toBe(400);
  });

  it('X-TENANT-ID STILL WORKS — with a real session behind it', async () => {
    // The other half. Removing this header would have broken 002/FR-013, and a
    // test that only proved the three are gone would not have noticed.
    const identity = await seedAuthIdentity(migration, 'standins-tenant-works');
    await migration.query(
      `INSERT INTO membership (identity_id, tenant_id, archetype) VALUES ($1, $2, 'SA')`,
      [identity.identityId, tenants.a],
    );

    signInOriginThrottle.reset();
    const credential = await request(app.getHttpServer())
      .post('/auth/sign-in')
      .send({ email: identity.email, password: TEST_CREDENTIAL });
    const factor = await request(app.getHttpServer())
      .post('/auth/factor')
      .send({
        challengeToken: credential.body.challengeToken,
        code: await generateAt(identity.secret, Math.floor(Date.now() / 1000)),
      });

    const response = await request(app.getHttpServer())
      .get('/tenant/invitations')
      .set('authorization', `Bearer ${factor.body.accessToken}`)
      .set('x-tenant-id', tenants.a);

    expect(response.status).toBe(200);
  });

  it('a session for one identity cannot be redirected by a stand-in naming another', async () => {
    // The attack the removal closes: hold a legitimate session, add the header
    // for somebody else, and see whose data comes back. The header is not read,
    // so the answer is your own.
    const mine = await seedAuthIdentity(migration, 'standins-mine');
    const theirs = await seedAuthIdentity(migration, 'standins-theirs');
    await migration.query(
      `INSERT INTO membership (identity_id, tenant_id, archetype) VALUES ($1, $2, 'AA'), ($3, $2, 'AA')`,
      [mine.identityId, tenants.a, theirs.identityId],
    );

    signInOriginThrottle.reset();
    const credential = await request(app.getHttpServer())
      .post('/auth/sign-in')
      .send({ email: mine.email, password: TEST_CREDENTIAL });
    const factor = await request(app.getHttpServer())
      .post('/auth/factor')
      .send({
        challengeToken: credential.body.challengeToken,
        code: await generateAt(mine.secret, Math.floor(Date.now() / 1000)),
      });

    const response = await request(app.getHttpServer())
      .get('/identity/memberships')
      .set('authorization', `Bearer ${factor.body.accessToken}`)
      .set('x-identity-id', theirs.identityId);

    expect(response.status).toBe(200);
    // Every membership returned belongs to the session's identity, not the
    // header's.
    const body = JSON.stringify(response.body);
    expect(body).not.toContain(theirs.identityId);
  });
});
